version: '3.1'
services:
    dynamodb-local:
        image: amazon/dynamodb-local:1.16.0
        platform: 'linux/amd64'
        ports:
            - 8000:8000
        command:
          - "-jar"
          - "DynamoDBLocal.jar"
          - "-inMemory"
          - "-sharedDb"

